spring:
  main:
    web-application-type: none
  application:
    name: commerce-batch
  profiles:
    active: local
  config:
    import:
      - jpa.yml
      - redis.yml
      - logging.yml
      - monitoring.yml

---
spring:
  config:
    activate:
      on-profile: local
  batch:
    jdbc:
      initialize-schema: always

---
spring:
  config:
    activate:
      on-profile: test
  batch:
    jdbc:
      initialize-schema: always

---
spring:
  config:
    activate:
      on-profile: dev
  batch:
    jdbc:
      initialize-schema: never

---
spring:
  config:
    activate:
      on-profile: qa
  batch:
    jdbc:
      initialize-schema: never

---
spring:
  config:
    activate:
      on-profile: prd
  batch:
    jdbc:
      initialize-schema: never
