server:
  shutdown: graceful
  tomcat:
    threads:
      max: 200 # 최대 워커 스레드 수 (default : 200)
      min-spare: 10 # 최소 유지 스레드 수 (default : 10)
    connection-timeout: 1m # 연결 타임아웃 (ms) (default : 60000ms = 1m)
    max-connections: 8192 # 최대 동시 연결 수 (default : 8192)
    accept-count: 100 # 대기 큐 크기 (default : 100)
    keep-alive-timeout: 60s # 60s
  max-http-request-header-size: 8KB

payment:
  callback-url: http://localhost:8080/api/v1/payments/callback

resilience4j:
  retry:
    instances:
      pg-simulator:
        max-attempts: 2
        wait-duration: 500ms
        retry-exceptions:
          - com.loopers.infrastructure.payment.pgsimulator.exception.PgSimulatorRetryableException
          - feign.RetryableException

  circuitbreaker:
    instances:
      pg-simulator:
        slow-call-rate-threshold: 50
        failure-rate-threshold: 50
        slow-call-duration-threshold: 700
        permitted-number-of-calls-in-half-open-state: 1
        max-wait-duration-in-half-open-state: 500
        sliding-window-type: time_based
        sliding-window-size: 10
        minimum-number-of-calls: 3
        wait-duration-in-open-state: 1000
        register-health-indicator: true

spring:
  main:
    web-application-type: servlet
  application:
    name: commerce-api
  profiles:
    active: local
  config:
    import:
      - jpa.yml
      - redis.yml
      - logging.yml
      - monitoring.yml

  cloud:
    openfeign:
      client:
        config:
          pg-simulator:
            connectTimeout: 3000
            readTimeout: 1000

springdoc:
  use-fqn: true
  swagger-ui:
    path: /swagger-ui.html

---
spring:
  config:
    activate:
      on-profile: local, test

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: qa

---
spring:
  config:
    activate:
      on-profile: prd

springdoc:
  api-docs:
    enabled: false
